### PR TITLE
lower the notification time by 1 hour

### PR DESCRIPTION
**Pull request by mickmcgrath13**
This was an hour late:
https://stackstorm-community.slack.com/archives/GQYG9VDRR/p1588698000296300

### CODE REVIEW

**Review by nmaludy — APPROVED** [review]
LGTM!

**Comment by arm4b** [comment]
New question is how to make the `@channel` actually work in Slack?

So the bot really notifies everyone.

**Comment by nmaludy** [comment]
@armab don't we have @here disabled unless special permissions are given? might need to just add the st2 user to that permissions group in slack?

**Comment by arm4b** [comment]
Not sure as it's bot.

https://stackoverflow.com/questions/42120115/how-do-i-send-here-with-the-slack-api might work?
```
<!here>
```

**Comment by arm4b** [comment]
When using `<!here>`:
```
 st2 run slack.chat.postMessage username='st2' channel="#tsc" text='<!here> Test' as_user=false
```
I got
```
Failed to perform action chat.postMessage: {"ok":false,"error":"restricted_action"}
```

As bots can't be managed as normal users, looks like some more manipulation needs to be done around Slack tokens + permissions :/
https://github.com/slackapi/template-announcement-approvals/issues/6#issuecomment-491390095

---

I'll drop the ball here as quick 5 min effort to fix it didn't work.

**Pull request merged**
